spring:
  datasource:
    url: ${DISCORD_SERVICE_DB_URL}
    username: app_user
    password: ${APP_DB_PASSWORD}
    hikari:
      schema: discord_service
  jpa:
    properties:
      hibernate:
        default_schema: discord_service
  flyway:
    enabled: true
    schemas: discord_service
    baseline-on-migrate: true
    locations: classpath:db/migration
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
server:
  port: 8088
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-response-size: 128

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      enabled: true

credentials:
  secret-key: ${DISCORD_SERVICE_ENCRYPTION_KEY}

security:
  jwt:
    secret: ${JWT_SECRET}