spring:
  datasource:
    url: ${WHATSAPP_SERVICE_DB_URL}
    username: app_user
    password: ${APP_DB_PASSWORD}
    hikari:
      schema: whatsapp_service

  jpa:
    properties:
      hibernate:
        default_schema: whatsapp_service

  flyway:
    enabled: true
    schemas: whatsapp_service
    baseline-on-migrate: true
    locations: classpath:db/migration
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      max-request-size: 128MB
server:
  port: 8087
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-response-size: 128

credentials:
  secret-key: ${WHATSAPP_SERVICE_ENCRYPTION_KEY}

security:
  jwt:
    secret: ${JWT_SECRET}